update_rate: 20
dataset:
  directory: basis
  file_extension: .mcap
sample_limit:
  size: 1000
  start_round: -1
sampler:
  name: airbot_mcap_sampler
  instance:
    _target_: airbot_ie.samplers.mcap_sampler.AIRBOTMcapDataSampler
    task_info:
      operator: Anonymous
      station: ptk-001
      task_name: anonymous task
      task_description: do some thing
      task_id: "135"
      skill:
        - pick
        - place
      object:
        - wooden_blocks
        - bowl
      scene: desktop
      subtasks:
        - skill: pick
          description: pick the wooden blocks from the bowl with the gripper
          description_zh: 用夹爪从碗中拾取木制积木
    upload:
      enable: false
      endpoint: 192.168.215.80
      username: admin
      password: "123456"
concurrent:
  actions: [update]
visualizers:
  names:
    - opencv
  instances:
    - _target_: airbot_data_collection.common.visualizers.opencv.OpenCVVisualizer
      rate: 30
      concurrent_mode: process
      key_filtering:
        include_endswith:
          - color/image_raw
          - depth/image_rect_raw
          - aligned_depth_to_color/image_raw

managers:
  names:
    - self_manager
    - keyboard
  instances:
    - _target_: airbot_data_collection.managers.basis.SelfManager
    - _target_: airbot_data_collection.managers.keyboard.KeyboardCallbackManager

fsm:
  _target_: airbot_ie.configs.fsm.get_fsm_config
