[build-system]
requires = ["setuptools<70.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "airbot-data-collection"
version = "0.6.5"
description = "AIRBOT Data Collection"
authors = [{ name = "OpenGHz", email = "your.email@example.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "pydantic",
    "numpy",
    "more-itertools",
    "typing-extensions",
    "setproctitle",
    "termcolor",
]

[project.optional-dependencies]
cv2 = ["opencv-python"]
rs = ["pyrealsense2"]
web = ["fastapi", "uvicorn"]
v4l2 = ["linuxpy", "PyTurboJPEG"]
udev = ["pyudev"]
mcap = ["mcap-data-loader"]
image = ["PyTurboJPEG", "av"]
basic = [
    "pydantic-settings",
    "omegaconf >=2.3.0",
    "hydra-zen",
    "transitions",
    "bidict",
    "pynput >=1.8.1",
    "tqdm",
    "send2trash >=1.8.3",
]
all = [
    "pydantic-settings",
    "omegaconf >=2.3.0",
    "hydra-zen",
    "transitions",
    "bidict",
    "pynput >=1.8.1",
    "tqdm",
    "opencv-python",
    # "pyrealsense2",
    "linuxpy",
    "PyTurboJPEG",
    "pyudev",
    "mcap-data-loader",
    "send2trash >=1.8.3",
]
# no hardware support, such as
# opencv, linuxpy, udev, pynput
# but pyav is included
soft = [
    "pydantic-settings",
    "omegaconf >=2.3.0",
    "hydra-zen",
    "transitions",
    "bidict",
    "tqdm",
    "mcap-data-loader",
    "send2trash >=1.8.3",
]
ml = ["torch", "torchvision"]
plt = ["ipykernel", "holoviews"]

[tool.setuptools.packages.find]
where = ["."]
include = ["airbot_data_collection*", "airbot_ie*"]

[project.scripts]
# Primary CLI: matches project name and is easy to discover/tab-complete
airbot-data-collection = "airbot_data_collection.main:main"
# Short alias for convenience
airdc = "airbot_data_collection.main:main"
