_target_: airbot_data_collection.airbot.robots.airbot_mmk.AIRBOTMMK

ip: "192.168.11.200"
components: ["left_arm", "left_arm_eef", "right_arm", "right_arm_eef", "head", "spine"]
cameras:
  - left_camera:
      rgb_camera.color_profile: 640,480,30
      enable_depth: false
  - right_camera:
      rgb_camera.color_profile: 640,480,30
      enable_depth: false
  - head_camera:
      rgb_camera.color_profile: 640,480,30
      enable_depth: false
