python3 main.py --path defaults/config.yaml \
                --components.names mmk \
                --components.paths airbot_mmk \
                --components.params '{}' \
                --components.roles o \
                --components.groups mmk \
                --dataset.directory example_task \
                --auto-control.rate 100 \
                --update-rate 20 \
                --sample-limit.start-round 0 \
                --sample-limit.size 1000