# @package _global_

demonstrator:
  name: grouped
  instance:
    _target_: airbot_data_collection.common.demonstrators.grouped.GroupedDemonstrator
    auto_control:
      groups: []
    components:
      groups:
        - /
      names:
        - camera
      instances:
        - _target_: airbot_data_collection.common.devices.cameras.intelrealsense.IntelRealSenseCamera
          camera_index: null
          height: 480
          width: 640
          enable_depth: true
          align_depth: true
          fps: 30
      roles:
        - o
dataset:
  directory: realsense
