# @package _global_

defaults:
  - /robots: airbot_play_with_name
  # - /key_remap: example
  - /key_remap@sampler.instance.key_remap: example
  - basis

remap_module: mcap_data_loader.utils.key
key_merge:
  method:
    _target_: mcap_data_loader.utils.basic.merge_data_stamped
  pred:
    _target_: mcap_data_loader.utils.dict.PredReplaceTo
    targets: [arm]
    sources:
      - [eef]
# ros1_init:
#   _target_: airdc.common.utils.ros.ros1.init_ros_node_safe
#   name: airbot_data_collection_node

sampler:
  name: airbot_mcap_sampler_ros
  instance:
    _target_: airdc.common.samplers.mcap_sampler_ros.McapDataSamplerROS
    video_save_to: folder
    av_coder:
      non_monotonic_mode: drop
      non_monotonic_log: false

demonstrator:
  instance:
    auto_control:
      rates: [100]
      modes: [process]
    components: null

# action_class: airdc.common.systems.grouped.GroupsSendActionConfig

# send_actions:
#   after_state_change:
#     active:
#       _target_: ${action_class}
#       groups:
#         - left
#         - right
#       action_values:
#         - [0, 0, 0, 0, 0, 0, 0]
#         - [0, 0, 0, 0, 0, 0, 0]

dataset:
  directory: ros
