# @package _global_

defaults:
  - post_capture@demonstrator.instance: "4"
  - /robots: airbot_play_mock

robot_cls: airbot.robots.airbot_play_mock.AIRBOTPlay

demonstrator:
  name: grouped
  instance:
    _target_: airbot_data_collection.demonstrate.demonstrators.grouped.GroupedDemonstrator
    auto_control:
      # groups: []
      rates: [100]
      modes: [process]
    components:
      groups:
        - left
        - left
        - right
        - right
        - /
      names:
        - lead
        - follow
        - lead
        - follow
        - env_camera
      instances:
        - "${merge_cfg:${robots}, {port: 50050}}"
        - "${merge_cfg:${robots}, {port: 50051}}"
        - "${merge_cfg:${robots}, {port: 50052}}"
        - "${merge_cfg:${robots}, {port: 50053}}"
        - _target_: airbot_data_collection.common.devices.cameras.v4l2.V4L2Camera
      roles:
        - l
        - f
        - l
        - f
        - o

dataset:
  directory: test
