_target_: airbot_data_collection.airbot.sensors.cameras.realsense.BsonRealSense
camera_index: null
fps: 30
width: 640
height: 480
use_depth: false
force_hardware_reset: true
color_mode: bgr
mock: false
