defaults:
  - /robots: airbot_play

demonstrator:
  name: grouped
  param:
    _target_: airbot_data_collection.demonstrate.demonstrators.grouped.GroupedDemonstrator
    auto_control:
      groups: []
    components:
      groups:
        - /
      # - /
      names:
        - ""
      # - follow_camera
      instances:
        - "${merge_cfg:${robots}, {port: 50051}}"
        # - _target_: airbot_data_collection.airbot.sensors.cameras.v4l2.V4L2Camera
      roles:
        - l
      # - o

dataset:
  directory: airbot_play
