demonstrator:
  name: grouped
  instance:
    _target_: airbot_data_collection.demonstrate.demonstrators.grouped.GroupedDemonstrator
    auto_control:
      groups: []
    components:
      groups:
        - /
      names:
        - camera
      instances:
        -
          camera_index: null
          height: 480
          width: 640
          enable_depth: true
          align_depth: true
      roles:
        # - f
        - o
dataset:
  directory: realsense
