sampler:
  name: airbot_mcap_sampler
  path: ""
  param:
    _target_: airbot_data_collection.airbot.samplers.mcap_sampler.AIRBOTMcapDataSampler
    task_info:
      task_id: 139

visualizers:
  names: [opencv]
  paths: ["", ""]
  params:
    - _target_: airbot_data_collection.airbot.visualizers.opencv.AIRBOTBsonOpenCVisualizer
      width: 640
      height: 480

managers:
  names:
    - self_manager
    - keyboard
  params:
    - _target_: airbot_data_collection.managers.basis.SelfManager
    - _target_: airbot_data_collection.managers.keyboard.KeyboardCallbackManager
  paths:
    - ""
    - ""

post_capture:
  2:
    /:
      keys:
        - "eef/joint_state/position"
        # - "arm/joint_state/position"
        # - "arm/joint_state/position"
      target_ranges:
        - 0: [0, 0.072] # G2
        # - 0: [-3.151, 2.080]  # play
        # - 0: [-2.74, 2.74]  # play_pro
  4:
    left:
      keys:
        - "eef/joint_state/position"
      target_ranges:
        - 0: [0, 0.072]
    right:
      keys:
        - "eef/joint_state/position"
      target_ranges:
        - 0: [0, 0.072]
