managers:
  names:
    - self_manager
    - keyboard
  params:
    - _target_: airbot_data_collection.managers.basis.SelfManager
    - _target_: airbot_data_collection.managers.keyboard.KeyboardCallbackManager
  paths:
    - ""
    - ""

sample_limit:
  size: 1000
  start_round: -1

sampler:
  name: airbot_mcap_sampler
  path: ""
  param:
    _target_: airbot_data_collection.airbot.samplers.mcap_sampler.AIRBOTMcapDataSampler
    task_info:
      operator: hanyang
      station: mmk-MK11QWZ025170023
      task_name: grasp place and stack wooden_blocks
      task_description: pick the wooden blocks from the bowl with the gripper,and place all wooden blocks on the desktop,and stack the wooden blocks one by one
      task_description_zh: 用夹爪从碗中拾取木制积木,将木制积木放置在桌面上,将木制积木逐个堆叠
      task_id: 120
      # 单个技能配置
      # skill: grasp
      # 多个技能配置示例 (取消注释并注释上面的单行配置):
      skill:
        - grasp
        - place
        - stack
      object:
        - wooden_blocks
        - bowl
      scene: desktop
      subtasks:
        - skill: grasp
          description: "pick the wooden blocks from the bowl with the gripper"
          description_zh: "用夹爪从碗中拾取木制积木"
        - skill: "place {A} on {B}"
          description: "place the wooden blocks on the desktop"
          description_zh: "将木制积木放置在桌面上"
        - skill: "stack {A} on {B}"
          description: "stack the wooden blocks one by one"
          description_zh: "将木制积木逐个堆叠"
    upload:
      enabled: false
      endpoint: 192.168.215.80
      username: admin
      password: "123456"

visualizers:
  names: [opencv]
  paths: [""]
  params:
    - _target_: airbot_data_collection.airbot.visualizers.opencv.AIRBOTBsonOpenCVisualizer
      width: 640
      height: 480
