auto_control:
  rate: 100
components:
  groups:
  - /
  - /
  - /
  - /
  names:
  - lead
  - follow
  - follow
  - env
  params:
  - port: 50050
  - port: 50051
  - camera_index: usb-0000:00:14.0-3.3
  - camera_index: usb-0000:00:14.0-2
  paths:
  - airbot_play
  - airbot_play
  - v4l2
  - v4l2
  roles:
  - l
  - f
  - o
  - o
dataset:
  directory: arm1-001
managers:
  names:
  - self_manager
  - keyboard
  params:
  - _target_: airbot_data_collection.managers.basis.SelfManager
  - _target_: airbot_data_collection.managers.keyboard.KeyboardCallbackManager
  paths:
  - ''
  - ''
sample_limit:
  size: 1000
  start_round: -1
sampler:
  name: airbot_mcap_sampler
  param:
    _target_: airbot_data_collection.airbot.samplers.mcap_sampler.AIRBOTMcapDataSampler
    info:
      operator: Anonymous
      station: ptk-001
      task:
        description: Put the cup on the plate on the desk.
        id: arm1-001
        name: put_cup
    save_type:
      depth: jpeg
      image: jpeg
  path: ''
update_rate: 20
visualizers:
  names:
  - opencv
  params:
  - _target_: airbot_data_collection.airbot.visualizers.opencv.AIRBOTBsonOpenCVisualizer
  paths:
  - ''
