sampler:
  name: airbot_bson_sampler
  path: ""
  param:
    _target_: airbot_data_collection.airbot.samplers.bson_sampler.AIRBOTBsonDataSampler

visualizers:
  names: [opencv]
  paths: ["", ""]
  params:
    - _target_: airbot_data_collection.airbot.visualizers.opencv.AIRBOTBsonOpenCVisualizer
      width: 320
      height: 240

managers:
  names: [self_manager, keyboard]
  paths: ["", ""]
  params:
    - _target_: airbot_data_collection.managers.basis.SelfManager
    - _target_: airbot_data_collection.managers.keyboard.KeyboardCallbackManager
